pipeline {
    agent any
    environment{
    C:\Sandeep_Work\QAAutomation\CICD\apache-maven-3.9.2-bin\apache-maven-3.9.2\bin
    }
 
    stages {
        stage('Build') {
            steps {
                bat "mvn -B compile"
            }
            
             stage('Test') {
              steps {
                bat "mvn -B clean install"
            }
         
            }
        }
    }
}
